/** Order email texts in the languages the shop emails support; anything else falls back to English. */
const strings = {
  en: {
    confirmationSubject: 'Order {{number}}',
    paidSubject: 'Payment received for order {{number}}',
    shippedSubject: 'Order {{number}} is on its way',
    cancelledSubject: 'Order {{number}} was cancelled',
    downloadsSubject: 'Your downloads for order {{number}}',
    newOrderSubject: 'New order {{number}}',
    thanks: 'Thank you for your order {{number}}.',
    paidText: 'We have received your payment for order {{number}}.',
    shippedText: 'Your order {{number}} has been shipped.',
    cancelledText: 'Your order {{number}} was cancelled. If you have already paid, we will contact you about the refund.',
    downloadsText: 'Here are your download links for order {{number}}.',
    item: 'Item',
    quantity: 'Quantity',
    price: 'Price',
    shipping: 'Shipping',
    paymentFee: 'Payment fee',
    total: 'Total',
    vatIncluded: 'Including VAT {{rate}} %: {{amount}}',
    payByTransfer: 'Pay by bank transfer',
    holder: 'Account holder',
    account: 'Account number',
    iban: 'IBAN',
    bic: 'BIC',
    amount: 'Amount',
    reference: 'Reference (variable symbol)',
    scanQr: 'You can also scan the attached QR code in your banking app.',
    cashOnDelivery: 'You will pay on delivery.',
    download: 'Download {{name}}',
    downloadLimit: 'Each link works for {{days}} days and up to {{limit}} downloads.',
    tracking: 'Tracking: {{tracking}}',
    qrFile: 'payment-{{number}}.png',
  },
  cs: {
    confirmationSubject: 'Objednávka {{number}}',
    paidSubject: 'Platba za objednávku {{number}} přijata',
    shippedSubject: 'Objednávka {{number}} je na cestě',
    cancelledSubject: 'Objednávka {{number}} byla zrušena',
    downloadsSubject: 'Soubory ke stažení k objednávce {{number}}',
    newOrderSubject: 'Nová objednávka {{number}}',
    thanks: 'Děkujeme za objednávku {{number}}.',
    paidText: 'Platbu za objednávku {{number}} jsme přijali.',
    shippedText: 'Objednávku {{number}} jsme odeslali.',
    cancelledText: 'Objednávka {{number}} byla zrušena. Pokud jste už zaplatili, ozveme se vám kvůli vrácení peněz.',
    downloadsText: 'Tady jsou odkazy ke stažení k objednávce {{number}}.',
    item: 'Položka',
    quantity: 'Množství',
    price: 'Cena',
    shipping: 'Doprava',
    paymentFee: 'Poplatek za platbu',
    total: 'Celkem',
    vatIncluded: 'Včetně DPH {{rate}} %: {{amount}}',
    payByTransfer: 'Zaplaťte převodem',
    holder: 'Majitel účtu',
    account: 'Číslo účtu',
    iban: 'IBAN',
    bic: 'BIC',
    amount: 'Částka',
    reference: 'Variabilní symbol',
    scanQr: 'Můžete také naskenovat přiložený QR kód v bankovní aplikaci.',
    cashOnDelivery: 'Zaplatíte při převzetí.',
    download: 'Stáhnout {{name}}',
    downloadLimit: 'Každý odkaz platí {{days}} dní a nejvýše pro {{limit}} stažení.',
    tracking: 'Sledování zásilky: {{tracking}}',
    qrFile: 'platba-{{number}}.png',
  },
} as const;

export type EmailKey = keyof (typeof strings)['en'];

export function emailText(language: string, key: EmailKey, vars: Record<string, string | number> = {}): string {
  const table = (strings as Record<string, Record<EmailKey, string>>)[language] ?? strings.en;
  return table[key].replace(/\{\{(\w+)\}\}/g, (_m, name: string) => String(vars[name] ?? ''));
}
